#!/bin/sh

set -eu

# shellcheck disable=SC1091
. /usr/local/etc/paperless/paperless.env

# Create media directories
mkdir -p "$PAPERLESS_INSTALL_DIR/consume"
mkdir -p "$PAPERLESS_INSTALL_DIR/media"

# Create and activate virtual environment
cd "$PAPERLESS_INSTALL_DIR"
python3.9 -m venv --system-site-packages venv
# shellcheck disable=SC1091
. venv/bin/activate

# Install dependencies
pip install --upgrade pip
pip install -r requirements.txt

# Migrate database
cd ./src
python3 manage.py migrate
DJANGO_SUPERUSER_PASSWORD="admin" python3 manage.py createsuperuser --noinput --email=root@localhost --username=admin
python3 -W ignore::RuntimeWarning -m nltk.downloader -d "$PAPERLESS_INSTALL_DIR /data/nltk" snowball_data
python3 -W ignore::RuntimeWarning -m nltk.downloader -d "$PAPERLESS_INSTALL_DIR /data/nltk" stopwords
python3 -W ignore::RuntimeWarning -m nltk.downloader -d "$PAPERLESS_INSTALL_DIR /data/nltk" punkt
cd -

# Fix for server Websockets (see https://github.com/paperless-ngx/paperless-ngx/issues/6349)
patch -R src/paperless/settings.py < /tmp/paperless_daphne.patch

deactivate
