#!/bin/sh

set -eux

# shellcheck disable=SC1091
. /usr/local/etc/paperless/paperless.env

# Create and activate virtual environment
cd "$PAPERLESS_INSTALL_DIR"
python3.11 -m venv --system-site-packages venv
# shellcheck disable=SC1091
. venv/bin/activate

# Install dependencies
pip install --upgrade pip
pip install -r requirements.txt

# Migrate database
cd ./src
python3 manage.py migrate
python3 -W ignore::RuntimeWarning -m nltk.downloader -d "$PAPERLESS_INSTALL_DIR/data/nltk" snowball_data
python3 -W ignore::RuntimeWarning -m nltk.downloader -d "$PAPERLESS_INSTALL_DIR/data/nltk" stopwords
python3 -W ignore::RuntimeWarning -m nltk.downloader -d "$PAPERLESS_INSTALL_DIR/data/nltk" punkt
cd -

# Fix for server Websockets (see https://github.com/paperless-ngx/paperless-ngx/issues/6349)
sed -i "" -e "/INSTALLED_APPS = / a\\$(printf "\n    \"daphne\",")" "$PAPERLESS_INSTALL_DIR/src/paperless/settings.py"

deactivate
