#!/bin/sh

set -eux

# shellcheck disable=SC1091
. /usr/local/etc/paperless/paperless.env

# Create and activate virtual environment
cd "$PAPERLESS_INSTALL_DIR"

# Install dependencies
tomlq --toml-output --in-place 'del(.tool.uv.environments)' pyproject.toml
uv sync --extra webserver

# WA: Fix bug with SQLite quoting (see https://code.djangoproject.com/ticket/35762)
if uv pip show django | grep -q "Version: 5.1.8"; then
    uv add django==5.2.1
fi

# Migrate database
cd ./src
uv run python manage.py migrate
uv run python -W ignore::RuntimeWarning -m nltk.downloader -d "$PAPERLESS_INSTALL_DIR/data/nltk" snowball_data
uv run python -W ignore::RuntimeWarning -m nltk.downloader -d "$PAPERLESS_INSTALL_DIR/data/nltk" stopwords
uv run python -W ignore::RuntimeWarning -m nltk.downloader -d "$PAPERLESS_INSTALL_DIR/data/nltk" punkt
cd -
