#!/bin/sh

# PROVIDE: paperlessconsumer
# REQUIRE: DAEMON redis
# KEYWORD: shutdown

# shellcheck disable=SC1091
. /etc/rc.subr
. /usr/local/etc/paperless/paperless.env

name="paperlessconsumer"
pidfile="/var/run/${name}.pid"
procname="$PAPERLESS_INSTALL_DIR/venv/bin/python3"

# RC variables
rcvar="${name}_enable"
paperlessconsumer_chdir="${PAPERLESS_INSTALL_DIR}/src"
command="/usr/sbin/daemon"
command_args="--syslog --close-fds --child-pidfile ${pidfile} --user paperless ${procname} manage.py document_consumer"
start_precmd="${name}_prestart"

paperlessconsumer_prestart() {
    . "$PAPERLESS_INSTALL_DIR/venv/bin/activate"
}

load_rc_config $name
run_rc_command "$1"
