#!/bin/sh

# PROVIDE: paperlesstaskqueue
# REQUIRE: DAEMON redis
# KEYWORD: shutdown

# shellcheck disable=SC1091
. /etc/rc.subr
. /usr/local/etc/paperless/paperless.env

name="paperlesstaskqueue"
pidfile="/var/run/${name}.pid"
procname="$PAPERLESS_INSTALL_DIR/venv/bin/python3"

# RC variables
rcvar="${name}_enable"
paperlesstaskqueue_chdir="${PAPERLESS_INSTALL_DIR}/src"
command="/usr/sbin/daemon"
command_args="--syslog --close-fds --child-pidfile ${pidfile} --user paperless ${procname} -m celery --app paperless worker --loglevel INFO"
start_precmd="${name}_prestart"

paperlesstaskqueue_prestart() {
    export CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1
    . "$PAPERLESS_INSTALL_DIR/venv/bin/activate"
}

load_rc_config $name
run_rc_command "$1"
