#!/bin/sh

# PROVIDE: paperlesswebserver
# REQUIRE: DAEMON redis
# KEYWORD: shutdown

# shellcheck disable=SC1091
. /etc/rc.subr
. /usr/local/etc/paperless/paperless.env

name="paperlesswebserver"
pidfile="/var/run/${name}.pid"
procname="/usr/local/bin/uv"

# RC variables
rcvar="${name}_enable"
paperlesswebserver_chdir="${PAPERLESS_INSTALL_DIR}/src"
command="/usr/sbin/daemon"
command_args="--syslog --close-fds --child-pidfile ${pidfile} --user paperless ${procname} run granian --interface asginl --ws paperless.asgi:application"
start_precmd="${name}_prestart"

paperlesswebserver_prestart() {
    export CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1

    # NOTE: See https://github.com/paperless-ngx/paperless-ngx/blob/dev/scripts/paperless-webserver.service
    # Host: GRANIAN_HOST -> PAPERLESS_BIND_ADDR -> default
    if [ -n "${PAPERLESS_BIND_ADDR:-}" ]; then export GRANIAN_HOST="$PAPERLESS_BIND_ADDR"; fi
    # Port: GRANIAN_PORT -> PAPERLESS_PORT -> default
    if [ -n "${PAPERLESS_PORT:-}" ]; then export GRANIAN_PORT="$PAPERLESS_PORT"; fi
    # Workers: GRANIAN_WORKERS -> PAPERLESS_WEBSERVER_WORKERS -> default
    if [ -n "${PAPERLESS_WEBSERVER_WORKERS:-}" ]; then export GRANIAN_WORKERS="$PAPERLESS_WEBSERVER_WORKERS"; fi
    # URL path prefix: only set if PAPERLESS_FORCE_SCRIPT_NAME exists
    if [ -n "${PAPERLESS_FORCE_SCRIPT_NAME:-}" ]; then export GRANIAN_URL_PATH_PREFIX="$PAPERLESS_FORCE_SCRIPT_NAME"; fi
}

load_rc_config $name
run_rc_command "$1"
