#!/bin/sh
set -eu

# shellcheck disable=SC1091
. /usr/local/etc/paperless/paperless.env

# shellcheck disable=SC1091
. "$PAPERLESS_INSTALL_DIR/venv/bin/activate"
cd "$PAPERLESS_INSTALL_DIR/src"
exec python3 manage.py document_consumer
