#!/bin/sh
set -eu

# shellcheck disable=SC1091
. /usr/local/etc/paperless/paperless.env

# shellcheck disable=SC1091
. "$PAPERLESS_INSTALL_DIR/venv/bin/activate"
cd "$PAPERLESS_INSTALL_DIR/src"
python3 -m celery --app paperless beat --loglevel INFO
